development:
  adapter: mysql2
  encoding: utf8
  database: theprofitjourney
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000
# 
# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
